// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OdontoCloud.Infrastructure.Data;

#nullable disable

namespace OdontoCloud.Infrastructure.Data.Migrations
{
    [DbContext(typeof(OdontoCloudDbContext))]
    [Migration("20260506181743_AddCrmKanbanStatusToPaciente")]
    partial class AddCrmKanbanStatusToPaciente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DentistaId")
                        .HasColumnType("uuid");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Procedimento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DentistaId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ClinicaId", "DentistaId", "DataHora");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Clinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Clinicas", (string)null);
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.ContaPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DentistaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FornecedorDestinatario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioBaixaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DentistaId");

                    b.HasIndex("ClinicaId", "Status", "DataVencimento");

                    b.ToTable("ContasPagar", (string)null);
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.ContaReceber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DentistaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ItemPlanoTratamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioBaixaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DentistaId");

                    b.HasIndex("ItemPlanoTratamentoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ClinicaId", "PacienteId", "Status");

                    b.ToTable("ContasReceber", (string)null);
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Dentista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgendaConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{\"inicio\":\"08:00\",\"fim\":\"18:00\",\"duracaoPadraoMinutos\":30,\"diasDaSemana\":[0,1,2,3,4,5,6]}");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegraComissaoJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{\"tipo\":\"PercentualFixo\",\"percentual\":30}");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId", "Nome");

                    b.ToTable("Dentistas", (string)null);
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.ItemPlanoTratamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DenteFdi")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Guid?>("DentistaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NumeroDente")
                        .HasColumnType("integer");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Procedimento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Orcado");

                    b.Property<string>("StatusOdontograma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DentistaId");

                    b.HasIndex("ProntuarioId");

                    b.HasIndex("ClinicaId", "PacienteId");

                    b.ToTable("ItensPlanoTratamento", (string)null);
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Convenio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<Guid?>("DentistaResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CrmKanbanStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelefoneWhatsapp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId", "Cpf")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Prontuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AnamneseAtualizadaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnamneseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DenticaoAtiva")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OdontogramaAtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OdontogramaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.HasIndex("ClinicaId", "PacienteId")
                        .IsUnique();

                    b.ToTable("Prontuarios", (string)null);
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.ProntuarioAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AlteradoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetalhesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoAlteracao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProntuarioId");

                    b.HasIndex("ClinicaId", "ProntuarioId");

                    b.ToTable("ProntuarioAuditorias", (string)null);
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId", "Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("OdontoCloud.Domain.Entities.Dentista", "Dentista")
                        .WithMany("Agendamentos")
                        .HasForeignKey("DentistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OdontoCloud.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dentista");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.ContaPagar", b =>
                {
                    b.HasOne("OdontoCloud.Domain.Entities.Dentista", "Dentista")
                        .WithMany("ContasPagar")
                        .HasForeignKey("DentistaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dentista");
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.ContaReceber", b =>
                {
                    b.HasOne("OdontoCloud.Domain.Entities.Dentista", "Dentista")
                        .WithMany("ContasReceber")
                        .HasForeignKey("DentistaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OdontoCloud.Domain.Entities.ItemPlanoTratamento", "ItemPlanoTratamento")
                        .WithMany()
                        .HasForeignKey("ItemPlanoTratamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OdontoCloud.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dentista");

                    b.Navigation("ItemPlanoTratamento");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.ItemPlanoTratamento", b =>
                {
                    b.HasOne("OdontoCloud.Domain.Entities.Dentista", "Dentista")
                        .WithMany("ItensPlanoTratamento")
                        .HasForeignKey("DentistaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OdontoCloud.Domain.Entities.Prontuario", "Prontuario")
                        .WithMany("ItensPlanoTratamento")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dentista");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Prontuario", b =>
                {
                    b.HasOne("OdontoCloud.Domain.Entities.Paciente", "Paciente")
                        .WithOne("Prontuario")
                        .HasForeignKey("OdontoCloud.Domain.Entities.Prontuario", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.ProntuarioAuditoria", b =>
                {
                    b.HasOne("OdontoCloud.Domain.Entities.Prontuario", "Prontuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Usuario", b =>
                {
                    b.OwnsMany("OdontoCloud.Domain.Permissions.UsuarioPermissao", "Permissoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Acao")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Modulo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<bool>("Permitido")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("UsuarioId");

                            b1.ToTable("UsuarioPermissoes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Dentista", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("ContasPagar");

                    b.Navigation("ContasReceber");

                    b.Navigation("ItensPlanoTratamento");
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("OdontoCloud.Domain.Entities.Prontuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("ItensPlanoTratamento");
                });
#pragma warning restore 612, 618
        }
    }
}
